import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ProductProvider from "./components/product-context";
import CartProvider from "./(a)/components/cartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
        <script src="https://cdn.tailwindcss.com"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"/>
        

        <style>

        </style>
    </head>
    <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >

    <CartProvider>

    <ProductProvider>
        {children}
    </ProductProvider>

    </CartProvider>

    </body>
    </html>
  );
}
